defaults:
  - base
  - _self_

module: cxrmate_ed.lightning_module
definition: FreezeEncoderPartialWarmStartOptimiser

mbatch_size: 8
accumulated_mbatch_size: null

max_epochs: 16

precision: 16-mixed
float32_matmul_precision: highest

warm_start_other_exp_trial_dir: experiments/cxrmate_ed/stage_1/trial_0
warm_start_optimiser: False
warm_start_ckpt_path_strict: False
allow_warm_start_optimiser_partial: True

tables_filter: ['mimic_cxr_sectioned', 'triage', 'medrecon']
prompt_report_sections_filter: ['indication', 'history']
add_time_deltas: True
