defaults:
  - base
  - _self_

module: cxrmate_ed.lightning_module
definition: Images

mbatch_size: 8
accumulated_mbatch_size: null

max_epochs: 32

precision: 16-mixed
float32_matmul_precision: highest
